/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Theme-aware colors using CSS variables
        primary: {
          DEFAULT: 'var(--ff-primary-500)',
          50: 'var(--ff-primary-50)',
          100: 'var(--ff-primary-100)',
          200: 'var(--ff-primary-200)',
          300: 'var(--ff-primary-300)',
          400: 'var(--ff-primary-400)',
          500: 'var(--ff-primary-500)',
          600: 'var(--ff-primary-600)',
          700: 'var(--ff-primary-700)',
          800: 'var(--ff-primary-800)',
          900: 'var(--ff-primary-900)',
          950: 'var(--ff-primary-950)',
        },
        secondary: {
          DEFAULT: 'var(--ff-secondary-500)',
          50: 'var(--ff-secondary-50)',
          100: 'var(--ff-secondary-100)',
          200: 'var(--ff-secondary-200)',
          300: 'var(--ff-secondary-300)',
          400: 'var(--ff-secondary-400)',
          500: 'var(--ff-secondary-500)',
          600: 'var(--ff-secondary-600)',
          700: 'var(--ff-secondary-700)',
          800: 'var(--ff-secondary-800)',
          900: 'var(--ff-secondary-900)',
          950: 'var(--ff-secondary-950)',
        },
        accent: {
          DEFAULT: 'var(--ff-accent-500)',
          50: 'var(--ff-accent-50)',
          100: 'var(--ff-accent-100)',
          200: 'var(--ff-accent-200)',
          300: 'var(--ff-accent-300)',
          400: 'var(--ff-accent-400)',
          500: 'var(--ff-accent-500)',
          600: 'var(--ff-accent-600)',
          700: 'var(--ff-accent-700)',
          800: 'var(--ff-accent-800)',
          900: 'var(--ff-accent-900)',
          950: 'var(--ff-accent-950)',
        },
        success: {
          DEFAULT: 'var(--ff-success-500)',
          50: 'var(--ff-success-50)',
          100: 'var(--ff-success-100)',
          200: 'var(--ff-success-200)',
          300: 'var(--ff-success-300)',
          400: 'var(--ff-success-400)',
          500: 'var(--ff-success-500)',
          600: 'var(--ff-success-600)',
          700: 'var(--ff-success-700)',
          800: 'var(--ff-success-800)',
          900: 'var(--ff-success-900)',
          950: 'var(--ff-success-950)',
        },
        warning: {
          DEFAULT: 'var(--ff-warning-500)',
          50: 'var(--ff-warning-50)',
          100: 'var(--ff-warning-100)',
          200: 'var(--ff-warning-200)',
          300: 'var(--ff-warning-300)',
          400: 'var(--ff-warning-400)',
          500: 'var(--ff-warning-500)',
          600: 'var(--ff-warning-600)',
          700: 'var(--ff-warning-700)',
          800: 'var(--ff-warning-800)',
          900: 'var(--ff-warning-900)',
          950: 'var(--ff-warning-950)',
        },
        error: {
          DEFAULT: 'var(--ff-error-500)',
          50: 'var(--ff-error-50)',
          100: 'var(--ff-error-100)',
          200: 'var(--ff-error-200)',
          300: 'var(--ff-error-300)',
          400: 'var(--ff-error-400)',
          500: 'var(--ff-error-500)',
          600: 'var(--ff-error-600)',
          700: 'var(--ff-error-700)',
          800: 'var(--ff-error-800)',
          900: 'var(--ff-error-900)',
          950: 'var(--ff-error-950)',
        },
        info: {
          DEFAULT: 'var(--ff-info-500)',
          50: 'var(--ff-info-50)',
          100: 'var(--ff-info-100)',
          200: 'var(--ff-info-200)',
          300: 'var(--ff-info-300)',
          400: 'var(--ff-info-400)',
          500: 'var(--ff-info-500)',
          600: 'var(--ff-info-600)',
          700: 'var(--ff-info-700)',
          800: 'var(--ff-info-800)',
          900: 'var(--ff-info-900)',
          950: 'var(--ff-info-950)',
        },
        // Neutral colors
        neutral: {
          DEFAULT: 'var(--ff-neutral-500)',
          50: 'var(--ff-neutral-50)',
          100: 'var(--ff-neutral-100)',
          200: 'var(--ff-neutral-200)',
          300: 'var(--ff-neutral-300)',
          400: 'var(--ff-neutral-400)',
          500: 'var(--ff-neutral-500)',
          600: 'var(--ff-neutral-600)',
          700: 'var(--ff-neutral-700)',
          800: 'var(--ff-neutral-800)',
          900: 'var(--ff-neutral-900)',
          950: 'var(--ff-neutral-950)',
        },
        // Legacy gray colors for compatibility
        gray: {
          50: 'var(--ff-neutral-50)',
          100: 'var(--ff-neutral-100)',
          200: 'var(--ff-neutral-200)',
          300: 'var(--ff-neutral-300)',
          400: 'var(--ff-neutral-400)',
          500: 'var(--ff-neutral-500)',
          600: 'var(--ff-neutral-600)',
          700: 'var(--ff-neutral-700)',
          800: 'var(--ff-neutral-800)',
          900: 'var(--ff-neutral-900)',
          950: 'var(--ff-neutral-950)',
        },
        // Background colors
        background: {
          primary: 'var(--ff-background-primary)',
          secondary: 'var(--ff-background-secondary)',
          tertiary: 'var(--ff-background-tertiary)',
          inverse: 'var(--ff-background-inverse)',
        },
        // Surface colors
        surface: {
          primary: 'var(--ff-surface-primary)',
          secondary: 'var(--ff-surface-secondary)',
          tertiary: 'var(--ff-surface-tertiary)',
          elevated: 'var(--ff-surface-elevated)',
          overlay: 'var(--ff-surface-overlay)',
        },
        // Border colors
        border: {
          primary: 'var(--ff-border-primary)',
          secondary: 'var(--ff-border-secondary)',
          subtle: 'var(--ff-border-subtle)',
          focus: 'var(--ff-border-focus)',
          error: 'var(--ff-border-error)',
          success: 'var(--ff-border-success)',
          warning: 'var(--ff-border-warning)',
        },
        // Text colors
        text: {
          primary: 'var(--ff-text-primary)',
          secondary: 'var(--ff-text-secondary)',
          tertiary: 'var(--ff-text-tertiary)',
          inverse: 'var(--ff-text-inverse)',
          disabled: 'var(--ff-text-disabled)',
          accent: 'var(--ff-text-accent)',
          success: 'var(--ff-text-success)',
          warning: 'var(--ff-text-warning)',
          error: 'var(--ff-text-error)',
        },
      },
      fontFamily: {
        sans: ['var(--ff-font-sans)', 'Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        serif: ['var(--ff-font-serif)', 'Georgia', 'serif'],
        mono: ['var(--ff-font-mono)', 'Monaco', 'Consolas', 'monospace'],
      },
      fontSize: {
        xs: 'var(--ff-text-xs)',
        sm: 'var(--ff-text-sm)',
        base: 'var(--ff-text-base)',
        lg: 'var(--ff-text-lg)',
        xl: 'var(--ff-text-xl)',
        '2xl': 'var(--ff-text-2xl)',
        '3xl': 'var(--ff-text-3xl)',
        '4xl': 'var(--ff-text-4xl)',
        '5xl': 'var(--ff-text-5xl)',
      },
      fontWeight: {
        light: 'var(--ff-font-light)',
        normal: 'var(--ff-font-normal)',
        medium: 'var(--ff-font-medium)',
        semibold: 'var(--ff-font-semibold)',
        bold: 'var(--ff-font-bold)',
      },
      lineHeight: {
        tight: 'var(--ff-leading-tight)',
        normal: 'var(--ff-leading-normal)',
        relaxed: 'var(--ff-leading-relaxed)',
      },
      spacing: {
        xs: 'var(--ff-spacing-xs)',
        sm: 'var(--ff-spacing-sm)',
        md: 'var(--ff-spacing-md)',
        lg: 'var(--ff-spacing-lg)',
        xl: 'var(--ff-spacing-xl)',
        '2xl': 'var(--ff-spacing-2xl)',
        '3xl': 'var(--ff-spacing-3xl)',
        '4xl': 'var(--ff-spacing-4xl)',
      },
      borderRadius: {
        sm: 'var(--ff-radius-sm)',
        md: 'var(--ff-radius-md)',
        lg: 'var(--ff-radius-lg)',
        xl: 'var(--ff-radius-xl)',
        '2xl': 'var(--ff-radius-2xl)',
        full: 'var(--ff-radius-full)',
      },
      boxShadow: {
        sm: 'var(--ff-shadow-sm)',
        md: 'var(--ff-shadow-md)',
        lg: 'var(--ff-shadow-lg)',
        xl: 'var(--ff-shadow-xl)',
        '2xl': 'var(--ff-shadow-2xl)',
        inner: 'var(--ff-shadow-inner)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'pulse-subtle': 'pulseSubtle 2s ease-in-out infinite',
        // VELOCITY theme animations
        'spin-slow': 'spin 3s linear infinite',
        'spin-fast': 'spin 0.5s linear infinite',
        'spin-reverse': 'spinReverse 1s linear infinite',
        'wave': 'wave 1.5s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'float': 'float 3s ease-in-out infinite',
        'fadeIn': 'fadeIn 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        pulseSubtle: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        // VELOCITY theme keyframes
        spinReverse: {
          '0%': { transform: 'rotate(360deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        wave: {
          '0%, 100%': { height: '20%' },
          '50%': { height: '100%' },
        },
        shimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(59, 130, 246, 0.5)' },
          '100%': { boxShadow: '0 0 20px rgba(59, 130, 246, 0.8), 0 0 30px rgba(59, 130, 246, 0.4)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
    },
  },
  plugins: [],
}