/**
 * Dashboard Configurations - Centralized configuration for all dashboard cards
 * Provides consistent card configurations across different dashboard types
 */

import { 
  FolderOpen, Users, CheckCircle, AlertTriangle, TrendingUp, Calendar,
  MapPin, Wifi, Activity, DollarSign, FileText,
  BarChart3, PieChart, Target, Clock, Truck, ShoppingCart,
  UserCheck, ClipboardList, Shield, Award, Database
} from 'lucide-react';
import { EnhancedStatCardProps } from '@/components/dashboard/EnhancedStatCard';

// 🟢 WORKING: Main Dashboard card configurations
export const getMainDashboardCards = (stats: any, trends: any, formatters: any): EnhancedStatCardProps[] => [
  {
    title: 'Active Projects',
    value: stats.activeProjects,
    icon: FolderOpen,
    color: '#3B82F6',
    trend: trends.activeProjects,
    subtitle: 'Currently in progress',
    description: 'Projects actively being worked on',
    route: '/app/projects',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Team Members',
    value: stats.teamMembers,
    icon: Users,
    color: '#10B981',
    trend: trends.teamMembers,
    subtitle: 'Active staff',
    description: 'Total active team members',
    route: '/app/staff',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Completed Tasks',
    value: stats.completedTasks,
    icon: CheckCircle,
    color: '#059669',
    trend: trends.completedTasks,
    subtitle: 'This month',
    description: 'Successfully completed tasks',
    route: '/app/tasks',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Open Issues',
    value: stats.openIssues,
    icon: AlertTriangle,
    color: '#F59E0B',
    trend: trends.openIssues,
    subtitle: 'Requires attention',
    description: 'Issues awaiting resolution',
    route: '/app/issues',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Poles Installed',
    value: stats.polesInstalled,
    icon: MapPin,
    color: '#8B5CF6',
    trend: trends.polesInstalled,
    subtitle: 'Total installed',
    description: 'Infrastructure deployment progress',
    route: '/app/projects/pole-tracker',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Total Revenue',
    value: stats.totalRevenue,
    icon: DollarSign,
    color: '#059669',
    trend: trends.totalRevenue,
    subtitle: 'This month',
    description: 'Revenue generated from projects',
    route: '/app/analytics',
    variant: 'detailed',
    formatValue: formatters.formatCurrency,
  },
];

// 🟢 WORKING: Contractors Dashboard card configurations
export const getContractorsDashboardCards = (stats: any, trends: any, formatters: any): EnhancedStatCardProps[] => [
  {
    title: 'Active Contractors',
    value: stats.contractorsActive,
    icon: UserCheck,
    color: '#3B82F6',
    trend: trends.contractorsActive,
    subtitle: 'Currently working',
    description: 'Contractors actively on projects',
    route: '/app/contractors',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Pending Applications',
    value: stats.contractorsPending,
    icon: Clock,
    color: '#F59E0B',
    trend: trends.contractorsPending,
    subtitle: 'Awaiting approval',
    description: 'New contractor applications',
    route: '/app/contractors?status=pending',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Performance Score',
    value: stats.performanceScore,
    icon: TrendingUp,
    color: '#10B981',
    trend: trends.performanceScore,
    subtitle: 'Average rating',
    description: 'Overall contractor performance',
    route: '/app/contractors/performance',
    variant: 'detailed',
    formatValue: formatters.formatPercentage,
  },
  {
    title: 'Quality Score',
    value: stats.qualityScore,
    icon: Award,
    color: '#8B5CF6',
    trend: trends.qualityScore,
    subtitle: 'Quality metrics',
    description: 'Work quality assessment',
    route: '/app/contractors/quality',
    variant: 'detailed',
    formatValue: formatters.formatPercentage,
  },
  {
    title: 'On-Time Delivery',
    value: stats.onTimeDelivery,
    icon: Calendar,
    color: '#059669',
    trend: trends.onTimeDelivery,
    subtitle: 'Schedule adherence',
    description: 'Projects completed on time',
    route: '/app/contractors/delivery',
    variant: 'detailed',
    formatValue: formatters.formatPercentage,
  },
  {
    title: 'Total Projects',
    value: stats.totalProjects,
    icon: FolderOpen,
    color: '#6B7280',
    trend: trends.totalProjects,
    subtitle: 'All assignments',
    description: 'Total project assignments',
    route: '/app/projects',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
];

// 🟢 WORKING: Procurement Dashboard card configurations  
export const getProcurementDashboardCards = (stats: any, trends: any, formatters: any): EnhancedStatCardProps[] => [
  {
    title: 'Active BOQs',
    value: stats.boqsActive,
    icon: ClipboardList,
    color: '#3B82F6',
    trend: trends.boqsActive,
    subtitle: 'Bills of Quantities',
    description: 'Currently active BOQs',
    route: '/app/procurement/boq',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Active RFQs',
    value: stats.rfqsActive,
    icon: ShoppingCart,
    color: '#8B5CF6',
    trend: trends.rfqsActive,
    subtitle: 'Request for Quotes',
    description: 'Open procurement requests',
    route: '/app/procurement/rfq',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Active Suppliers',
    value: stats.supplierActive,
    icon: Truck,
    color: '#10B981',
    trend: trends.supplierActive,
    subtitle: 'Verified suppliers',
    description: 'Active supplier partnerships',
    route: '/app/suppliers',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Budget Utilization',
    value: stats.budgetUtilization,
    icon: PieChart,
    color: '#F59E0B',
    trend: trends.budgetUtilization,
    subtitle: 'Budget consumed',
    description: 'Current budget utilization',
    route: '/app/procurement/budget',
    variant: 'detailed',
    formatValue: formatters.formatPercentage,
  },
  {
    title: 'Procurement Value',
    value: stats.totalRevenue,
    icon: DollarSign,
    color: '#059669',
    trend: trends.totalRevenue,
    subtitle: 'Total value',
    description: 'Value of active procurements',
    route: '/app/procurement/analytics',
    variant: 'detailed',
    formatValue: formatters.formatCurrency,
  },
  {
    title: 'Pending Issues',
    value: stats.openIssues,
    icon: AlertTriangle,
    color: '#EF4444',
    trend: trends.openIssues,
    subtitle: 'Requires attention',
    description: 'Procurement issues to resolve',
    route: '/app/procurement/issues',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
];

// 🟢 WORKING: Analytics Dashboard card configurations (enhanced)
export const getAnalyticsDashboardCards = (stats: any, trends: any, formatters: any): EnhancedStatCardProps[] => [
  {
    title: 'Total Poles',
    value: stats.polesInstalled,
    icon: MapPin,
    color: '#3B82F6',
    trend: trends.polesInstalled,
    subtitle: 'Infrastructure deployed',
    description: 'Total poles installed across projects',
    route: '/app/projects/pole-tracker',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Total Drops',
    value: stats.dropsCompleted,
    icon: Wifi,
    color: '#8B5CF6',
    trend: trends.dropsCompleted,
    subtitle: 'Connections made',
    description: 'Customer connections completed',
    route: '/app/projects/drops',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Fiber Installed',
    value: stats.fiberInstalled,
    icon: Activity,
    color: '#F59E0B',
    trend: trends.fiberInstalled,
    subtitle: 'Meters deployed',
    description: 'Total fiber optic cable installed',
    route: '/app/projects/fiber',
    variant: 'detailed',
    formatValue: (value: number) => `${formatters.formatNumber(value)}m`,
  },
  {
    title: 'Revenue',
    value: stats.totalRevenue,
    icon: DollarSign,
    color: '#10B981',
    trend: trends.totalRevenue,
    subtitle: 'Total earnings',
    description: 'Revenue from all projects',
    route: '/app/analytics/revenue',
    variant: 'detailed',
    formatValue: formatters.formatCurrency,
  },
  {
    title: 'Active Teams',
    value: stats.teamMembers,
    icon: Users,
    color: '#059669',
    trend: trends.teamMembers,
    subtitle: 'Working teams',
    description: 'Teams currently active',
    route: '/app/staff/teams',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
];

// 🟢 WORKING: Reports Dashboard card configurations
export const getReportsDashboardCards = (stats: any, trends: any, formatters: any): EnhancedStatCardProps[] => [
  {
    title: 'Reports Generated',
    value: stats.reportsGenerated,
    icon: FileText,
    color: '#3B82F6',
    trend: trends.reportsGenerated,
    subtitle: 'This month',
    description: 'Reports created and generated',
    route: '/app/reports',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Active Projects',
    value: stats.activeProjects,
    icon: FolderOpen,
    color: '#8B5CF6',
    trend: trends.activeProjects,
    subtitle: 'Being tracked',
    description: 'Projects included in reports',
    route: '/app/projects',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Revenue Tracked',
    value: stats.totalRevenue,
    icon: DollarSign,
    color: '#10B981',
    trend: trends.totalRevenue,
    subtitle: 'Financial data',
    description: 'Revenue tracked in reports',
    route: '/app/reports/financial',
    variant: 'detailed',
    formatValue: formatters.formatCurrency,
  },
  {
    title: 'Performance Score',
    value: stats.performanceScore,
    icon: TrendingUp,
    color: '#F59E0B',
    trend: trends.performanceScore,
    subtitle: 'Overall rating',
    description: 'Average performance metrics',
    route: '/app/reports/performance',
    variant: 'detailed',
    formatValue: formatters.formatPercentage,
  },
  {
    title: 'Data Points',
    value: stats.completedTasks,
    icon: Database,
    color: '#6B7280',
    trend: trends.completedTasks,
    subtitle: 'Tracked metrics',
    description: 'Total data points collected',
    route: '/app/reports/data',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Team Coverage',
    value: stats.teamMembers,
    icon: Shield,
    color: '#059669',
    trend: trends.teamMembers,
    subtitle: 'Members reporting',
    description: 'Team members in reports',
    route: '/app/reports/teams',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
];

// 🟢 WORKING: KPI Dashboard card configurations
export const getKPIDashboardCards = (stats: any, trends: any, formatters: any): EnhancedStatCardProps[] => [
  {
    title: 'Performance Score',
    value: stats.performanceScore,
    icon: BarChart3,
    color: '#3B82F6',
    trend: trends.performanceScore,
    subtitle: 'Overall KPI',
    description: 'Consolidated performance metric',
    route: '/app/kpi/performance',
    variant: 'detailed',
    formatValue: formatters.formatPercentage,
  },
  {
    title: 'Quality Score',
    value: stats.qualityScore,
    icon: Target,
    color: '#10B981',
    trend: trends.qualityScore,
    subtitle: 'Quality metrics',
    description: 'Work quality assessment',
    route: '/app/kpi/quality',
    variant: 'detailed',
    formatValue: formatters.formatPercentage,
  },
  {
    title: 'On-Time Delivery',
    value: stats.onTimeDelivery,
    icon: Calendar,
    color: '#8B5CF6',
    trend: trends.onTimeDelivery,
    subtitle: 'Schedule adherence',
    description: 'Projects delivered on time',
    route: '/app/kpi/delivery',
    variant: 'detailed',
    formatValue: formatters.formatPercentage,
  },
  {
    title: 'Budget Efficiency',
    value: stats.budgetUtilization,
    icon: DollarSign,
    color: '#F59E0B',
    trend: trends.budgetUtilization,
    subtitle: 'Budget utilization',
    description: 'Efficient budget usage',
    route: '/app/kpi/budget',
    variant: 'detailed',
    formatValue: formatters.formatPercentage,
  },
  {
    title: 'Team Productivity',
    value: stats.teamMembers,
    icon: Users,
    color: '#059669',
    trend: trends.teamMembers,
    subtitle: 'Active contributors',
    description: 'Productive team members',
    route: '/app/kpi/teams',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
  {
    title: 'Project Success',
    value: stats.activeProjects,
    icon: Award,
    color: '#DC2626',
    trend: trends.activeProjects,
    subtitle: 'Success rate',
    description: 'Successfully completed projects',
    route: '/app/kpi/projects',
    variant: 'detailed',
    formatValue: formatters.formatNumber,
  },
];

// 🟢 WORKING: Dashboard type mapping
export const getDashboardCards = (
  dashboardType: 'main' | 'contractors' | 'procurement' | 'analytics' | 'reports' | 'kpi',
  stats: any,
  trends: any,
  formatters: any
): EnhancedStatCardProps[] => {
  switch (dashboardType) {
    case 'main':
      return getMainDashboardCards(stats, trends, formatters);
    case 'contractors':
      return getContractorsDashboardCards(stats, trends, formatters);
    case 'procurement':
      return getProcurementDashboardCards(stats, trends, formatters);
    case 'analytics':
      return getAnalyticsDashboardCards(stats, trends, formatters);
    case 'reports':
      return getReportsDashboardCards(stats, trends, formatters);
    case 'kpi':
      return getKPIDashboardCards(stats, trends, formatters);
    default:
      return getMainDashboardCards(stats, trends, formatters);
  }
};