/**
 * Procurement Seed Data - BOQ (Bill of Quantities) Data
 * Sample BOQs, BOQ Items, and BOQ Exceptions for development and testing
 */

import { BOQ, BOQItem, BOQException } from '../../neon/schema';
import { 
  MOCK_PROJECT_IDS, 
  MOCK_USER_IDS, 
  TIME_CONSTANTS,
  CABLE_SPECS,
  HARDWARE_SPECS,
  PROCUREMENT_STATUS
} from './constants';

const { NOW, YESTERDAY, LAST_WEEK } = TIME_CONSTANTS;

// =============================================
// BOQ SEED DATA
// =============================================

export const SEED_BOQS: Omit<BOQ, 'id'>[] = [
  {
    projectId: MOCK_PROJECT_IDS.FIBRE_NETWORK_A,
    version: 'v1.0',
    title: 'Fibre Network Phase 1 BOQ',
    description: 'Bill of quantities for the first phase of fibre network deployment',
    status: 'approved',
    mappingStatus: 'completed',
    mappingConfidence: '95.5',
    uploadedBy: MOCK_USER_IDS.PROJECT_MANAGER,
    uploadedAt: LAST_WEEK,
    fileName: 'Fibre_Network_Phase1_BOQ.xlsx',
    fileUrl: 'https://storage.example.com/boqs/fibre_network_phase1.xlsx',
    fileSize: 524288,
    approvedBy: MOCK_USER_IDS.PROCUREMENT_MANAGER,
    approvedAt: YESTERDAY,
    itemCount: 25,
    mappedItems: 24,
    unmappedItems: 1,
    exceptionsCount: 1,
    totalEstimatedValue: '2850000.00',
    currency: 'ZAR',
    rejectionReason: null,
    rejectedBy: null,
    rejectedAt: null,
    createdAt: LAST_WEEK,
    updatedAt: YESTERDAY,
  },
  {
    projectId: MOCK_PROJECT_IDS.FIBRE_NETWORK_B,
    version: 'v2.1',
    title: 'Fibre Network Phase 2 BOQ - Revised',
    description: 'Revised bill of quantities for phase 2 after client feedback',
    status: 'mapping_review',
    mappingStatus: 'in_progress',
    mappingConfidence: '78.2',
    uploadedBy: MOCK_USER_IDS.PROJECT_MANAGER,
    uploadedAt: NOW,
    fileName: 'Fibre_Network_Phase2_BOQ_v2.1.xlsx',
    fileUrl: 'https://storage.example.com/boqs/fibre_network_phase2_v2.xlsx',
    fileSize: 768432,
    itemCount: 42,
    mappedItems: 28,
    unmappedItems: 14,
    exceptionsCount: 3,
    totalEstimatedValue: '4200000.00',
    currency: 'ZAR',
    approvedBy: null,
    approvedAt: null,
    rejectionReason: null,
    rejectedBy: null,
    rejectedAt: null,
    createdAt: NOW,
    updatedAt: NOW,
  }
];

export const SEED_BOQ_ITEMS: Omit<BOQItem, 'id' | 'boqId'>[] = [
  // Items for BOQ 1
  {
    projectId: MOCK_PROJECT_IDS.FIBRE_NETWORK_A,
    lineNumber: 1,
    itemCode: 'CABLE-SM-12F',
    description: 'Single Mode Fibre Optic Cable - 12 Core',
    category: 'Cables',
    subcategory: 'Fibre Optic',
    quantity: "5000.0000",
    uom: 'meter',
    unitPrice: "45.50",
    totalPrice: "227500.00",
    phase: 'Phase 1',
    task: 'Cable Installation',
    site: 'Main Route',
    location: 'Underground',
    catalogItemId: 'cat_cable_sm_12f_001',
    catalogItemCode: 'SM12F-STD',
    catalogItemName: 'Standard Single Mode 12 Core Cable',
    mappingConfidence: "98.5",
    mappingStatus: 'mapped',
    specifications: CABLE_SPECS.SINGLE_MODE_12F,
    technicalNotes: 'ITU-T G.652.D compliant',
    alternativeItems: null,
    procurementStatus: PROCUREMENT_STATUS.RFQ_CREATED,
    createdAt: LAST_WEEK,
    updatedAt: YESTERDAY,
  },
  {
    projectId: MOCK_PROJECT_IDS.FIBRE_NETWORK_A,
    lineNumber: 2,
    itemCode: 'SPLICE-TRAY',
    description: 'Fibre Splice Tray - 12 Core Capacity',
    category: 'Hardware',
    subcategory: 'Splice Components',
    quantity: "120.0000",
    uom: 'piece',
    unitPrice: "125.00",
    totalPrice: "15000.00",
    phase: 'Phase 1',
    task: 'Splicing',
    site: 'All Sites',
    location: 'Cabinets',
    catalogItemId: 'cat_splice_tray_12c_001',
    catalogItemCode: 'ST12C-STD',
    catalogItemName: 'Standard 12 Core Splice Tray',
    mappingConfidence: "95.0",
    mappingStatus: 'mapped',
    specifications: HARDWARE_SPECS.SPLICE_TRAY_12,
    procurementStatus: PROCUREMENT_STATUS.PENDING,
    technicalNotes: null,
    alternativeItems: null,
    createdAt: LAST_WEEK,
    updatedAt: LAST_WEEK,
  },
  {
    projectId: MOCK_PROJECT_IDS.FIBRE_NETWORK_A,
    lineNumber: 3,
    itemCode: null,
    description: 'Custom Network Termination Box - Special Configuration',
    category: 'Hardware',
    subcategory: 'Termination',
    location: null,
    catalogItemId: null,
    catalogItemCode: null,
    catalogItemName: null,
    quantity: "50.0000",
    uom: 'piece',
    unitPrice: "350.00",
    totalPrice: "17500.00",
    phase: 'Phase 1',
    task: 'Termination',
    site: 'Customer Premises',
    mappingConfidence: "45.0",
    mappingStatus: 'exception',
    specifications: {
      ports: 4,
      type: 'SC/APC',
      mounting: 'Wall Mount',
      protection: 'IP65'
    },
    technicalNotes: 'Custom configuration - requires vendor specification',
    alternativeItems: null,
    procurementStatus: PROCUREMENT_STATUS.PENDING,
    createdAt: LAST_WEEK,
    updatedAt: LAST_WEEK,
  },
  {
    projectId: MOCK_PROJECT_IDS.FIBRE_NETWORK_A,
    lineNumber: 4,
    itemCode: 'CLOSURE-IL-48F',
    description: 'Inline Fibre Optic Closure - 48 Core Capacity',
    category: 'Hardware',
    subcategory: 'Closures',
    quantity: "25.0000",
    uom: 'piece',
    unitPrice: "850.00",
    totalPrice: "21250.00",
    phase: 'Phase 1',
    task: 'Joint Installation',
    site: 'Main Route',
    location: 'Underground',
    catalogItemId: 'cat_closure_inline_48c_001',
    catalogItemCode: 'CL48F-IL',
    catalogItemName: 'Inline 48 Core Fibre Closure',
    mappingConfidence: "92.0",
    mappingStatus: 'mapped',
    specifications: HARDWARE_SPECS.CLOSURE_INLINE,
    technicalNotes: 'Weather resistant, IP68 rated',
    alternativeItems: [
      {
        catalogItemId: 'cat_closure_inline_48c_002',
        catalogItemName: 'Premium Inline 48 Core Closure',
        confidence: "88.0"
      }
    ],
    procurementStatus: PROCUREMENT_STATUS.QUOTED,
    createdAt: LAST_WEEK,
    updatedAt: YESTERDAY,
  },
  {
    projectId: MOCK_PROJECT_IDS.FIBRE_NETWORK_B,
    lineNumber: 1,
    itemCode: 'CABLE-SM-24F',
    description: 'Single Mode Fibre Optic Cable - 24 Core',
    category: 'Cables',
    subcategory: 'Fibre Optic',
    quantity: "8000.0000",
    uom: 'meter',
    unitPrice: "72.00",
    totalPrice: "576000.00",
    phase: 'Phase 2',
    task: 'Trunk Cable Installation',
    site: 'Backbone Route',
    location: 'Underground',
    catalogItemId: 'cat_cable_sm_24f_001',
    catalogItemCode: 'SM24F-STD',
    catalogItemName: 'Standard Single Mode 24 Core Cable',
    mappingConfidence: "99.0",
    mappingStatus: 'mapped',
    specifications: CABLE_SPECS.SINGLE_MODE_24F,
    technicalNotes: 'ITU-T G.652.D compliant, armored for direct burial',
    alternativeItems: null,
    procurementStatus: PROCUREMENT_STATUS.PENDING,
    createdAt: NOW,
    updatedAt: NOW,
  }
];

export const SEED_BOQ_EXCEPTIONS: Omit<BOQException, 'id' | 'boqId' | 'boqItemId'>[] = [
  {
    projectId: MOCK_PROJECT_IDS.FIBRE_NETWORK_A,
    exceptionType: 'no_match',
    severity: 'medium',
    issueDescription: 'Custom Network Termination Box with special configuration not found in catalog',
    suggestedAction: 'Review with procurement team for custom sourcing or find alternative',
    systemSuggestions: [
      {
        catalogItemId: 'cat_term_box_4p_001',
        catalogItemName: 'Standard 4 Port Termination Box',
        confidence: "65.0",
        notes: 'Standard option - may need modification'
      },
      {
        catalogItemId: 'cat_term_box_custom_001',
        catalogItemName: 'Custom Termination Box - Made to Order',
        confidence: "85.0",
        notes: 'Custom solution - longer lead time'
      }
    ],
    status: 'open',
    priority: 'medium',
    assignedTo: MOCK_USER_IDS.PROCUREMENT_MANAGER,
    assignedAt: YESTERDAY,
    resolvedBy: null,
    resolvedAt: null,
    resolutionNotes: null,
    resolutionAction: null,
    createdAt: YESTERDAY,
    updatedAt: YESTERDAY,
  },
  {
    projectId: MOCK_PROJECT_IDS.FIBRE_NETWORK_B,
    exceptionType: 'multiple_matches',
    severity: 'low',
    issueDescription: 'Multiple cable specifications found with similar characteristics',
    suggestedAction: 'Select preferred specification or request clarification from client',
    systemSuggestions: [
      {
        catalogItemId: 'cat_cable_sm_24f_001',
        catalogItemName: 'Standard Single Mode 24 Core Cable',
        confidence: "95.0",
        notes: 'Most common specification'
      },
      {
        catalogItemId: 'cat_cable_sm_24f_002',
        catalogItemName: 'Premium Single Mode 24 Core Cable',
        confidence: "92.0",
        notes: 'Higher specification - better performance'
      }
    ],
    status: 'in_review',
    priority: 'low',
    assignedTo: MOCK_USER_IDS.PROJECT_MANAGER,
    assignedAt: NOW,
    resolvedBy: null,
    resolvedAt: null,
    resolutionNotes: null,
    resolutionAction: null,
    createdAt: NOW,
    updatedAt: NOW,
  }
];